PREFIX ric: <http://www.ica.org/standards/RiC/ontology#>
PREFIX dct: <http://purl.org/dc/terms/>

DELETE {
    ?record a ric:RecordSet .
}
INSERT{
    ?record a ric:Record .
}
WHERE {

?record a ric:RecordSet .

MINUS {
    ?recordSet a ric:RecordSet ;
        dct:relation ?record .
}
}